apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: london-tube-lines
  labels:
          #name: london-tube-lines-frontend
          #labels:
    app.kubernetes.io/name: london-tube-lines-frontend
    app.kubernetes.io/part-of: london-tube-lines
    app.kubernetes.io/created-by: alir-zi
    app.kubernetes.io/env: Production
    app.kubernetes.io/unique-token: zi-my-zpp
    app.kubernetes.io/namespace: london-tube-lines
spec:
  rules:
  - host: test.20302040.xyz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: london-tube-lines-frontend
            port: 
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: london-tube-lines-frontend
  labels:
     app.kubernetes.io/name: london-tube-lines-frontend
     app.kubernetes.io/part-of: london-tube-lines
     app.kubernetes.io/created-by: alir-zi
     app.kubernetes.io/env: Production
     app.kubernetes.io/unique-token: zi-my-zpp
     app.kubernetes.io/namespace: london-tube-lines
spec:
  type: ClusterIP
  selector:
     app.kubernetes.io/name: london-tube-lines-frontend
     app.kubernetes.io/part-of: london-tube-lines
     app.kubernetes.io/created-by: alir-zi
     app.kubernetes.io/env: Production
     app.kubernetes.io/unique-token: zi-my-zpp
     app.kubernetes.io/namespace: london-tube-lines
  ports:
  - port: 80
    name: http
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: london-tube-lines-frontend
  labels:
     app.kubernetes.io/name: london-tube-lines-frontend
     app.kubernetes.io/part-of: london-tube-lines
     app.kubernetes.io/created-by: alir-zi
     app.kubernetes.io/env: Production
     app.kubernetes.io/unique-token: zi-my-zpp
     app.kubernetes.io/namespace: london-tube-lines
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: london-tube-lines-frontend
      app.kubernetes.io/part-of: london-tube-lines
      app.kubernetes.io/created-by: alir-zi
      app.kubernetes.io/env: Production
      app.kubernetes.io/unique-token: zi-my-zpp
      app.kubernetes.io/namespace: london-tube-lines
  template:
    metadata:
      labels:
        app.kubernetes.io/name: london-tube-lines-frontend
        app.kubernetes.io/part-of: london-tube-lines
        app.kubernetes.io/created-by: alir-zi
        app.kubernetes.io/env: Production
        app.kubernetes.io/unique-token: zi-my-zpp
        app.kubernetes.io/namespace: london-tube-lines
    spec:
       containers:
         - name: backend
           image: ssbostan/london-tube-lines-frontend:latest
           ports:
             - containerPort: 8080
           env:
             - name: LONDON_TUBE_LINES_BACKEND_HOST_ADDR
               value: london-tube-lines-backend