apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    name: alpine
spec:
  containers:
  - name: alpine
    image: alpine:latest
    volumeMounts:
      - name: root
        mountPath: /data
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
    - name: root
      hostPath:
        path: /