apiVersion: v1
kind: Service
metadata:
  name: london-tube-lines-backend
  labels:
     app.kubernetes.io/name: london-tube-lines-backend
     app.kubernetes.io/part-of: london-tube-lines
     app.kubernetes.io/created-by: alir-zi
     app.kubernetes.io/env: Production
     app.kubernetes.io/unique-token: zi-my-zpp
     app.kubernetes.io/namespace: london-tube-lines
spec:
  type: ClusterIP
  selector:
     app.kubernetes.io/name: london-tube-lines-backend
     app.kubernetes.io/part-of: london-tube-lines
     app.kubernetes.io/created-by: alir-zi
     app.kubernetes.io/env: Production
     app.kubernetes.io/unique-token: zi-my-zpp
     app.kubernetes.io/namespace: london-tube-lines
  ports:
  - port: 80
    name: http
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: london-tube-lines-backend
  labels:
     app.kubernetes.io/name: london-tube-lines-backend
     app.kubernetes.io/part-of: london-tube-lines
     app.kubernetes.io/created-by: alir-zi
     app.kubernetes.io/env: Production
     app.kubernetes.io/unique-token: zi-my-zpp
     app.kubernetes.io/namespace: london-tube-lines
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: london-tube-lines-backend
      app.kubernetes.io/part-of: london-tube-lines
      app.kubernetes.io/created-by: alir-zi
      app.kubernetes.io/env: Production
      app.kubernetes.io/unique-token: zi-my-zpp
      app.kubernetes.io/namespace: london-tube-lines
  template:
    metadata:
      labels:
        app.kubernetes.io/name: london-tube-lines-backend
        app.kubernetes.io/part-of: london-tube-lines
        app.kubernetes.io/created-by: alir-zi
        app.kubernetes.io/env: Production
        app.kubernetes.io/unique-token: zi-my-zpp
        app.kubernetes.io/namespace: london-tube-lines
    spec:
       containers:
         - name: backend
           image: ssbostan/london-tube-lines-backend:latest
           ports:
             - containerPort: 8080